---
# tasks file for install_dependencies

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: Install build-essential
  action: apt pkg=build-essential
  become: true

- name: Download go installer
  get_url:
    url: https://gist.githubusercontent.com/jdkanani/e18e14910652ad829fad994e4b89f0b9/raw/aecdd859f568848083b4db6cc1ee2bc1b8090ed3/go-install.sh
    dest: "{{ ansible_env.HOME }}/go-install.sh"

- name: Execute the go-install.sh
  command: "bash go-install.sh"
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: Remove the go-install.sh
  file:
    path: "{{ ansible_env.HOME }}/go-install.sh"
    state: absent

- name: Creating symlink for golang
  file:
    src: "{{ ansible_env.HOME }}/.go/bin/go"
    dest: "/usr/bin/go"
    state: link
  become: true

- name: Install jq
  action: apt pkg=jq
  become: true

- name: Install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: present
  become: true
